version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jobhunter
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  db_data: